apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
data:
  telegraf.conf: |-
    [[inputs.nginx]]
      urls = ["http://localhost/nginx_status"]
    [[outputs.prometheus_client]]
      ## Address to listen on.
      listen = ":9273"

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    commit: {{COMMIT_HASH}}
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
      - name: telegraf-config-volume
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: frontend-config
          items:
          - key: telegraf.conf
            path: telegraf.conf
      containers:
      - image: webmakersteve/myamtech-frontend:latest
        imagePullPolicy: Always
        name: frontend
        env:
        - name: COMMIT
          value: {{COMMIT_HASH}}
        ports:
        - containerPort: 80
          protocol: TCP
      - image: telegraf
        name: telegraf
        ports:
        - containerPort: 9273
          protocol: TCP
          name: metrics
        volumeMounts:
        - name: telegraf-config-volume
          mountPath: /etc/telegraf
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  - port: 9273
    protocol: TCP
    targetPort: 9273
    name: metrics
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  rules:
  - host: www.myamtech.io
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        path: /
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  namespace: monitoring
  labels:
    app: frontend
    release: prom
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: metrics
    interval: 15s